CREATE TABLE `test_data_exchange_item_info` (
  `id` bigint(20) NOT NULL COMMENT '事项ID',
  `sxbh` varchar(38) DEFAULT NULL COMMENT '编号规则：类别+日期+6位随机码',
  `sxmd` varchar(20) DEFAULT NULL COMMENT '事项目的：咨询、建议、申诉、求决',
  `bt` varchar(300) DEFAULT NULL COMMENT '事项标题：事项形式+姓名+问题属地',
  `calledphone` varchar(48) DEFAULT NULL COMMENT '被叫号码',
  `callphone` varchar(48) DEFAULT NULL COMMENT '来电号码',
  `created_time` datetime(6) DEFAULT NULL COMMENT '创建时间：数据生成时间',
  `djbm` varchar(255) DEFAULT NULL COMMENT '登记部门',
  `djbmdm` bigint(20) DEFAULT NULL COMMENT '登记部门代码',
  `djjgdm` varchar(100) DEFAULT NULL COMMENT '登记机构代码',
  `djjgjb` varchar(1) DEFAULT NULL COMMENT '登记机构级别：1、国家级 2、省级 3、市级 4、区级',
  `djjgmc` varchar(300) DEFAULT NULL COMMENT '登记机构名称',
  `djr` varchar(50) DEFAULT NULL COMMENT '登记人姓名',
  `djrdm` bigint(20) DEFAULT NULL COMMENT '登记人代码',
  `djsj` datetime(6) DEFAULT NULL COMMENT '登记时间：创建时间以后的1小时之内',
  `fjsl` smallint(6) DEFAULT NULL COMMENT '附件数量：根据生成的附件来计算',
  `gkbz` varchar(2) DEFAULT NULL COMMENT '是否公开：0：否 1：是',
  `hyfl` varchar(30) DEFAULT NULL COMMENT '行业分类',
  `hyflmc` varchar(50) DEFAULT NULL COMMENT '行业分类名称',
  `isbm` varchar(2) DEFAULT NULL COMMENT '是否保密：0：否 1：是',
  `issq` varchar(2) DEFAULT NULL COMMENT '是否涉企：0：否 1：是',
  `nmbz` varchar(2) DEFAULT NULL COMMENT '是否匿名：0：否 1：是',
  `nrfl` varchar(30) DEFAULT NULL COMMENT '内容分类',
  `tsnr` longtext COMMENT '投诉内容：随机问题生成',
  `update_time` datetime(6) DEFAULT NULL COMMENT '更新时间：数据更新后的更新时间',
  `wtsd` varchar(256) DEFAULT NULL COMMENT '问题属地',
  `wtsd_addr` varchar(100) DEFAULT NULL COMMENT '问题属地地址',
  `sxrq` datetime(6) DEFAULT NULL COMMENT '事项日期：数据生成日期',
  `sxrs` varchar(10) DEFAULT NULL COMMENT '事项人数：该投诉问题的人数',
  `sxxs` varchar(3) DEFAULT NULL COMMENT '事项形式：信、访、网、电',
  `xm` varchar(48) DEFAULT NULL COMMENT '姓名',
  `fjbh` varchar(200) DEFAULT NULL COMMENT '附件编号：如果有对应文件，则对应文件的编码',
  `yjly` varchar(100) DEFAULT NULL COMMENT '原件来源：101：人民网，102：国家政务服务平台，103：国家信访局',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '抽取增量时间戳',
  `local_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '本地入库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_item_info_id` (`id`),
  KEY `idx_item_info_update_time` (`update_time`),
  KEY `idx_item_info_created_time` (`created_time`),
  KEY `idx_item_info_sxbh` (`sxbh`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业务库事项件表-切换后新';

CREATE TABLE `test_data_exchange_people_info` (
`id` bigint(20) NOT NULL COMMENT '事项人ID',
`sxbh` varchar(38) DEFAULT NULL COMMENT '来自事项库的事项编号',
`xm` varchar(50) DEFAULT NULL COMMENT '事项人姓名',
`mz` varchar(2) DEFAULT NULL COMMENT '事项人民族',
`sjh` varchar(20) DEFAULT NULL COMMENT '手机号码',
`xb` varchar(1) DEFAULT NULL COMMENT '事项人性别,0：女  1：男',
`xh` varchar(3) DEFAULT NULL COMMENT '序号',
`yzbm` varchar(10) DEFAULT NULL COMMENT '邮政编码',
`zjhm` varchar(20) DEFAULT NULL COMMENT '证件号码',
`zjlx` varchar(2) DEFAULT NULL COMMENT '证件类型',
`zy` varchar(2) DEFAULT NULL COMMENT '职业',
`zz` varchar(200) DEFAULT NULL COMMENT '事项人详细住址',
`zzdm` varchar(100) DEFAULT NULL COMMENT '事项人住址行政区划代码',
`zzmm` varchar(20) DEFAULT NULL COMMENT '政治面貌',
`zzzw` varchar(100) DEFAULT NULL COMMENT '事项人住址行政区划中文',
`create_time` datetime DEFAULT NULL COMMENT '创建时间',
`update_time` datetime DEFAULT NULL COMMENT '更新时间',
`timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '抽取增量时间戳'
PRIMARY KEY (`id`),
UNIQUE KEY `dwd_sx_people_info_pkey` USING BTREE (`id`),
KEY `auto_shard_key_sxbh` USING BTREE (`sxbh`)

)COMMENT '事项人员表';

CREATE TABLE `test_data_exchange_item_process_info` (
`id` bigint(20) NOT NULL COMMENT '主键id',
`sxbh` varchar(38) DEFAULT NULL COMMENT '事项编号',
`blfs` varchar(6) DEFAULT NULL COMMENT '办理方式',
`bljgdm` varchar(100) DEFAULT NULL COMMENT '办理机构代码',
`bljg` varchar(200) DEFAULT NULL COMMENT '办理机构',
`dept_id` bigint(20) DEFAULT NULL COMMENT '办理部门id',
`dept_name` varchar(200) DEFAULT NULL COMMENT '办理部门名称',
`user_id` bigint(20) DEFAULT NULL COMMENT '经办人id',
`user_name` varchar(60) DEFAULT NULL COMMENT '经办人',
`blsj` datetime DEFAULT NULL COMMENT '办理时间',
`dfnr` text COMMENT '答复内容',
`fjsl` bigint(20) DEFAULT NULL COMMENT '附件数量',
`fjbh` bigint(20) DEFAULT NULL COMMENT '附件编号',
`update_time` datetime DEFAULT NULL COMMENT '更新时间',
`create_time` datetime DEFAULT NULL COMMENT '创建时间',
`timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '抽取增量时间戳',
`local_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '抽取到本地时间',
PRIMARY KEY (`id`),
UNIQUE KEY `visit_petition_process_pkey` USING BTREE (`id`),
KEY `auto_shard_key_id` USING BTREE (`id`),
KEY `dwd_sx_item_process_info_xfjbh` USING BTREE (`sxbh`)

) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT '事项事项办理记录表'  ;

CREATE TABLE `test_data_exchange_sx_attach` (
`id` bigint(20) NOT NULL COMMENT '主键',
`sxbh` varchar(64) DEFAULT NULL COMMENT '事项件编号',
`link` text COMMENT '附件地址',
`name` varchar(500) DEFAULT NULL COMMENT '附件名称',
`original_name` varchar(500) DEFAULT NULL COMMENT '附件原名',
`extension` varchar(12) DEFAULT NULL COMMENT '附件拓展名',
`attach_size` bigint(20) DEFAULT NULL COMMENT '附件大小',
`create_time` datetime DEFAULT NULL COMMENT '创建时间',
`full_path` text COMMENT '文件完整路径',
`timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '抽取增量时间戳',
PRIMARY KEY (`id`),
UNIQUE KEY `visit_attach_pkey` USING BTREE (`id`),
KEY `auto_shard_key_id` USING BTREE (`id`),
KEY `index_update_time` (`update_time`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT '附件表';


CREATE TABLE `test_data_exchange_ws_item_info` (
`id` bigint(20) NOT NULL COMMENT '事项ID',
`sxbh` varchar(38) DEFAULT NULL COMMENT '编号规则：',
`sxmd` varchar(20) DEFAULT NULL COMMENT '事项目的',
`bt` varchar(300) DEFAULT NULL COMMENT '事项标题',
`created_time` datetime(6) DEFAULT NULL COMMENT '创建时间',
`fjsl` smallint(6) DEFAULT NULL COMMENT '附件数量',
`gkbz` varchar(2) DEFAULT NULL COMMENT '是否公开0：否? 1: 是',
`hyfl` varchar(30) DEFAULT NULL COMMENT '行业分类',
`hyflmc` varchar(50) DEFAULT NULL COMMENT '行业分类名称',
`isbm` varchar(2) DEFAULT NULL COMMENT '是否保密0：否? 1: 是',
`issq` varchar(2) DEFAULT NULL COMMENT '是否涉企0：否? 1: 是',
`nmbz` varchar(2) DEFAULT NULL COMMENT '是否匿名0：否? 1: 是',
`nrfl` varchar(30) DEFAULT NULL COMMENT '内容分类',
`tsnr` longtext COMMENT '投诉内容',
`update_time` datetime(6) DEFAULT NULL COMMENT '更新时间',
`wtsd` varchar(256) DEFAULT NULL COMMENT '问题属地',
`wtsd_addr` varchar(100) DEFAULT NULL COMMENT '问题属地地址',
`sxrq` datetime(6) DEFAULT NULL COMMENT '事项日期',
`sxrs` varchar(10) DEFAULT NULL COMMENT '事项人数',
`sxxs` varchar(3) DEFAULT NULL COMMENT '事项形式',
`xm` varchar(48) DEFAULT NULL COMMENT '姓名',
`yjly` varchar(100) DEFAULT NULL COMMENT '原件来源',
`zjhm` varchar(100) DEFAULT NULL COMMENT '证件号码',
  `sjh` varchar(100) DEFAULT NULL COMMENT '手机号',
  `zjlx` varchar(100) DEFAULT NULL COMMENT '证件类型',
`timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '抽取增量时间戳',
`local_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '本地入库时间',
PRIMARY KEY (`id`),
UNIQUE KEY `index_pkey_id` USING BTREE (`id`),
KEY `index_update_time` USING BTREE (`update_time`),
KEY `index_created_time` (`created_time`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT '业务库事项件表-网上';


CREATE TABLE `test_city_exchange_in_shaox_hotline_rxgd` (
  `caller_id` varchar(32) NOT NULL COMMENT '来电编号',
  `user_name` varchar(32) NOT NULL COMMENT '姓名',
  `gender` varchar(32) NOT NULL COMMENT '性别(0未知性别1男性2女性9未说明性别)',
  `id_type` varchar(32) DEFAULT NULL COMMENT '证件类型',
  `id_no` varchar(32) DEFAULT NULL COMMENT '证件号码',
  `called_phone` varchar(32) NOT NULL COMMENT '被叫号码',
  `tel_phone` varchar(32) NOT NULL COMMENT '联系电话',
  `income_phone` varchar(32) NOT NULL COMMENT '来电号码',
  `usual_address` varchar(1024) DEFAULT NULL COMMENT '常住地址',
  `usual_address_id` varchar(12) NOT NULL COMMENT '常住地址代码',
  `residence_address` varchar(1024) DEFAULT NULL COMMENT '户籍地址',
  `letter_date` datetime NOT NULL COMMENT '民呼日期',
  `company_tag` varchar(1) DEFAULT NULL COMMENT '是否为企业(0:否,1:是)',
  `company_name` varchar(32) DEFAULT NULL COMMENT '企业名称',
  `enrollment_method` varchar(32) NOT NULL COMMENT '事项形式(电)',
  `title` varchar(128) NOT NULL COMMENT '标题',
  `letter_aim` varchar(32) NOT NULL COMMENT '事项目的',
  `suggest_tag` varchar(1) DEFAULT NULL COMMENT '是否建议(0:否,1:是)',
  `content_type` varchar(32) NOT NULL COMMENT '内容分类',
  `problem_source` varchar(12) NOT NULL COMMENT '问题属地代码(行政区划编码)',
  `problem_occurrence` varchar(500) NOT NULL COMMENT '问题发生地',
  `open_tag` varchar(1) NOT NULL COMMENT '是否公开(0:否,1:是)',
  `anonymus_tag` varchar(5) NOT NULL COMMENT '是否匿名(0:否,1:是)',
  `data_type` varchar(32) NOT NULL COMMENT '数据类型(1.人工服务2.智能服务)',
  `cue_of_time` datetime DEFAULT NULL COMMENT '事项限办时间',
  `enrollment_id` varchar(32) NOT NULL COMMENT '登记人ID',
  `enrollment_name` varchar(32) NOT NULL COMMENT '登记人姓名',
  `enrollment_time` datetime NOT NULL COMMENT '登记时间',
  `enrollment_unit` varchar(32) NOT NULL COMMENT '登记单位',
  `submit_content` varchar(2000) NOT NULL COMMENT '反映诉求内容',
  `reply_content` varchar(2000) DEFAULT NULL COMMENT '处理情况',
  `created_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_time` datetime DEFAULT NULL COMMENT '更新时间',
  `source_phone` varchar(32) DEFAULT NULL COMMENT '源被叫号码',
  `industry_sort` varchar(32) DEFAULT NULL COMMENT '行业内容分类',
  `zyhy` varchar(10) DEFAULT NULL COMMENT '专业行业',
  `isbm` varchar(2) NOT NULL COMMENT '是否保密(0:否,1:是)',
  `jjcd` varchar(5) NOT NULL COMMENT '紧急程度(1.快速2.一般)',
  `sjly` varchar(12) DEFAULT NULL COMMENT '数据来源(行政区划编码)',
  `yjly` varchar(3) NOT NULL COMMENT '原件来源(热线12345各城市代码)',
  `local_create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '本地入库时间',
  `local_update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '本地更新时间',
  PRIMARY KEY (`caller_id`) USING BTREE,
  UNIQUE KEY `caller_id` (`caller_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='热线工单信息';
