CREATE TABLE test_data_exchange_item_info (
    id VARCHAR(64) PRIMARY KEY COMMENT '事项ID',
    sxbh VARCHAR(50) NOT NULL COMMENT '事项编号',
    sxmd VARCHAR(20) COMMENT '事目的',
    bt VARCHAR(500) COMMENT '事项标题',
    calledphone VARCHAR(20) COMMENT '被叫号码',
    callphone VARCHAR(20) COMMENT '来电号码',
    created_time DATETIME COMMENT '创建时间',
    djbm VARCHAR(100) COMMENT '登记部门',
    djbmdm VARCHAR(20) COMMENT '登记部门代码',
    djjgdm VARCHAR(20) COMMENT '登记机构代码',
    djjgjb TINYINT COMMENT '登记机构级别',
    djjgmc VARCHAR(100) COMMENT '登记机构名称',
    djr VARCHAR(50) COMMENT '登记人姓名',
    djrdm VARCHAR(50) COMMENT '登记人代码',
    djsj DATETIME COMMENT '登记时间',
    fjsl INT COMMENT '附件数量',
    gkbz TINYINT COMMENT '是否公开',
    hyfl VARCHAR(20) COMMENT '行业分类',
    hyflmc VARCHAR(100) COMMENT '行业分类名称',
    isbm TINYINT COMMENT '是否保密',
    issq TINYINT COMMENT '是否涉企',
    nmbz TINYINT COMMENT '是否匿名',
    nrfl VARCHAR(20) COMMENT '内容分类',
    tsnr TEXT COMMENT '投诉内容',
    update_time DATETIME COMMENT '更新时间',
    wtsd VARCHAR(20) COMMENT '问题属地',
    wtsd_addr VARCHAR(200) COMMENT '问题属地地址',
    sxrq DATE COMMENT '事项日期',
    sxrs INT COMMENT '事项人数',
    sxxs VARCHAR(10) COMMENT '事项形式',
    xm VARCHAR(50) COMMENT '姓名',
    fjbh VARCHAR(100) COMMENT '附件编号',
    yjly VARCHAR(20) COMMENT '原件来源',
    timestamp DATETIME COMMENT '抽取增量时间戳',
    local_timestamp DATETIME COMMENT '本地入库时间'
) COMMENT '业务库事项件表';

CREATE TABLE test_data_exchange_people_info (
    id VARCHAR(64) PRIMARY KEY COMMENT '事项人ID',
    sxbh VARCHAR(50) NOT NULL COMMENT '事项编号',
    xm VARCHAR(50) COMMENT '事项人姓名',
    mz VARCHAR(20) COMMENT '民族',
    sjh VARCHAR(20) COMMENT '手机号码',
    xb TINYINT COMMENT '性别',
    xh INT COMMENT '序号',
    yzbm VARCHAR(10) COMMENT '邮政编码',
    zjhm VARCHAR(50) COMMENT '证件号码',
    zjlx TINYINT COMMENT '证件类型',
    zy VARCHAR(100) COMMENT '职业',
    zz VARCHAR(200) COMMENT '详细住址',
    zzdm VARCHAR(20) COMMENT '住址行政区划代码',
    zzmm VARCHAR(50) COMMENT '政治面貌',
    zzzw VARCHAR(100) COMMENT '住址行政区划中文',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    timestamp DATETIME COMMENT '抽取增量时间戳'
) COMMENT '事项人员表';

CREATE TABLE test_data_exchange_item_process_info (
    id VARCHAR(64) PRIMARY KEY COMMENT '主键ID',
    sxbh VARCHAR(50) NOT NULL COMMENT '事项编号',
    blfs VARCHAR(20) COMMENT '办理方式',
    bljgdm VARCHAR(20) COMMENT '办理机构代码',
    bljg VARCHAR(100) COMMENT '办理机构',
    dept_id VARCHAR(50) COMMENT '办理部门ID',
    dept_name VARCHAR(100) COMMENT '办理部门名称',
    user_id VARCHAR(50) COMMENT '经办人ID',
    user_name VARCHAR(50) COMMENT '经办人姓名',
    blsj DATETIME COMMENT '办理时间',
    dfnr TEXT COMMENT '答复内容',
    fjsl INT COMMENT '附件数量',
    fjbh VARCHAR(100) COMMENT '附件编号',
    update_time DATETIME COMMENT '更新时间',
    create_time DATETIME COMMENT '创建时间',
    timestamp DATETIME COMMENT '抽取增量时间戳',
    local_timestamp DATETIME COMMENT '抽取到本地时间'
) COMMENT '事项事项办理记录表';

CREATE TABLE test_data_exchange_sx_attach (
    id VARCHAR(64) PRIMARY KEY COMMENT '主键ID',
    sxbh VARCHAR(50) NOT NULL COMMENT '事项件编号',
    link VARCHAR(500) COMMENT '附件地址',
    name VARCHAR(200) COMMENT '附件名称',
    original_name VARCHAR(200) COMMENT '附件原名',
    extension VARCHAR(20) COMMENT '附件拓展名',
    attach_size INT COMMENT '附件大小(KB)',
    create_time DATETIME COMMENT '创建时间',
    full_path VARCHAR(500) COMMENT '文件完整路径',
    timestamp DATETIME COMMENT '抽取增量时间戳'
) COMMENT '附件表';

CREATE TABLE test_data_exchange_ws_item_info (
    id VARCHAR(64) PRIMARY KEY COMMENT '事项ID',
    sxbh VARCHAR(50) NOT NULL COMMENT '事项编号',
    sxmd VARCHAR(20) COMMENT '事目的',
    bt VARCHAR(500) COMMENT '事项标题',
    created_time DATETIME COMMENT '创建时间',
    fjsl INT COMMENT '附件数量',
    gkbz TINYINT COMMENT '是否公开',
    hyfl VARCHAR(20) COMMENT '行业分类',
    hyflmc VARCHAR(100) COMMENT '行业分类名称',
    isbm TINYINT COMMENT '是否保密',
    issq TINYINT COMMENT '是否涉企',
    nmbz TINYINT COMMENT '是否匿名',
    nrfl VARCHAR(20) COMMENT '内容分类',
    tsnr TEXT COMMENT '投诉内容',
    update_time DATETIME COMMENT '更新时间',
    wtsd VARCHAR(20) COMMENT '问题属地',
    wtsd_addr VARCHAR(200) COMMENT '问题属地地址',
    sxrq DATE COMMENT '事项日期',
    sxrs INT DEFAULT 1 COMMENT '事项人数',
    sxxs VARCHAR(10) DEFAULT '网' COMMENT '事项形式',
    xm VARCHAR(50) COMMENT '姓名',
    yjly VARCHAR(20) COMMENT '原件来源',
    zjhm VARCHAR(50) COMMENT '证件号码',
    sjh VARCHAR(20) COMMENT '手机号',
    zjlx VARCHAR(20) DEFAULT '居民身份证' COMMENT '证件类型',
    timestamp DATETIME COMMENT '抽取增量时间戳',
    local_timestamp DATETIME COMMENT '本地入库时间'
) COMMENT '业务库事项件表 - 网上';

CREATE TABLE test_city_exchange_in_shaox_hotline_rxgd (
    caller_id VARCHAR(50) PRIMARY KEY COMMENT '来电编号',
    user_name VARCHAR(50) COMMENT '姓名',
    gender TINYINT COMMENT '性别',
    id_type VARCHAR(20) COMMENT '证件类型',
    id_no VARCHAR(50) COMMENT '证件号码',
    called_phone VARCHAR(20) COMMENT '被叫号码',
    tel_phone VARCHAR(20) COMMENT '联系电话',
    income_phone VARCHAR(20) COMMENT '来电号码',
    usual_address VARCHAR(200) COMMENT '常住地址',
    usual_address_id VARCHAR(20) COMMENT '常住地址代码',
    residence_address VARCHAR(200) COMMENT '户籍地址',
    letter_date DATE COMMENT '民呼日期',
    company_tag TINYINT COMMENT '是否为企业',
    company_name VARCHAR(100) COMMENT '企业名称',
    enrollment_method VARCHAR(10) DEFAULT '电' COMMENT '事项形式',
    title VARCHAR(500) COMMENT '标题',
    letter_aim VARCHAR(20) COMMENT '事目的',
    suggest_tag TINYINT COMMENT '是否建议',
    content_type VARCHAR(20) COMMENT '内容分类',
    problem_source VARCHAR(20) COMMENT '问题属地代码',
    problem_occurrence VARCHAR(200) COMMENT '问题发生地',
    open_tag TINYINT COMMENT '是否公开',
    anonymus_tag TINYINT COMMENT '是否匿名',
    data_type TINYINT DEFAULT 1 COMMENT '数据类型',
    cue_of_time DATE COMMENT '事项限办时间',
    enrollment_id VARCHAR(50) COMMENT '登记人ID',
    enrollment_name VARCHAR(50) COMMENT '登记人姓名',
    enrollment_time DATETIME COMMENT '登记时间',
    enrollment_unit VARCHAR(100) COMMENT '登记单位',
    submit_content TEXT COMMENT '反映诉求内容',
    reply_content TEXT COMMENT '处理情况',
    created_time DATETIME COMMENT '创建时间',
    updated_time DATETIME COMMENT '更新时间',
    source_phone VARCHAR(20) COMMENT '源被叫号码',
    industry_sort VARCHAR(20) COMMENT '行业内容分类',
    zyhy VARCHAR(20) COMMENT '专业行业',
    isbm TINYINT COMMENT '是否保密',
    jjcd TINYINT DEFAULT 2 COMMENT '紧急程度',
    sjly VARCHAR(20) COMMENT '数据来源',
    yjly VARCHAR(20) COMMENT '原件来源'
) COMMENT '热线工单信息';