version: '3.8'

services:
  app:
    image: isap_fake_data:V1
    container_name: isap-fake-data
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_SERVER=172.16.10.196
      - POSTGRES_PORT=5432
      - POSTGRES_USER=isap_admin
      - POSTGRES_PASSWORD=113RfkdsDMDb6H7T
      - POSTGRES_DB=isap_admin
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge