from django.shortcuts import render
from django.http import HttpResponse, StreamingHttpResponse
# 导入 Customer 对象定义
from common.models import Customer, Medicine, Order
from openai import OpenAI
import json
import markdown
from django.core.cache import cache
from django.template import engines

def deepseek_stream_view(request):
    message = request.GET.get('msg', '请分析当前仓库产品的报关风险')
    
    # ------------------------- 智能扫描仓库产品 -------------------------
    # 获取仓库中的所有药品信息
    medicines = Medicine.objects.all()
    inventory_info = "当前仓库产品清单：\n"
    if medicines.exists():
        for medicine in medicines:
            inventory_info += f"- 产品名称: {medicine.name}, 编号: {medicine.sn}, 描述: {medicine.desc}\n"
    else:
        inventory_info = "当前仓库为空。\n"
    # ------------------------------------------------------------------

    sty = f"""你是一个专业的海关报关助手。
你的任务是根据用户的提问，结合当前的仓库产品清单，提供专业的报关建议、风险预警或HS编码归类建议。
如果用户询问库存情况，请根据清单回答。

{inventory_info}
"""

    def event_stream():
        # Yield initial HTML with styles and scripts
        yield """
        <!DOCTYPE html>
        <html lang="zh">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>海关报关智能分析 (Markdown)</title>
            <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; background: #f4f7f6; color: #24292e; padding: 20px; line-height: 1.6; }
                .container { max-width: 800px; margin: 0 auto; background: #fff; padding: 40px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); }
                h1 { color: #0366d6; border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; margin-top: 0; }
                .markdown-body { font-size: 16px; }
                .markdown-body blockquote { padding: 0 1em; color: #6a737d; border-left: 0.25em solid #dfe2e5; margin: 0; }
                .markdown-body code { padding: 0.2em 0.4em; background: #f6f8fa; border-radius: 6px; font-family: monospace; }
                .markdown-body pre { padding: 16px; overflow: auto; background: #f6f8fa; border-radius: 6px; }
                .markdown-body table { border-collapse: collapse; width: 100%; margin-bottom: 16px; }
                .markdown-body th, .markdown-body td { padding: 6px 13px; border: 1px solid #dfe2e5; }
                .markdown-body tr:nth-child(2n) { background: #f6f8fa; }
                .footer { margin-top: 30px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>📦 智能报关分析报告</h1>
                <div id="render-target" class="markdown-body">正在生成...</div>
                <div class="footer">Generated by DeepSeek AI &bull; B2B Customs System</div>
            </div>
            
            <div id="raw-stream" style="display:none;">
            <script>
                // Remove this script tag from the DOM immediately so it doesn't get parsed as text
                document.currentScript.remove();

                // Now observe the parent (which is the raw-stream div)
                // Since we removed the script, we need to find the raw-stream by ID
                const rawStream = document.getElementById('raw-stream');
                const renderTarget = document.getElementById('render-target');
                
                const update = () => {
                    if (window.marked && rawStream) {
                        renderTarget.innerHTML = marked.parse(rawStream.innerText);
                    }
                };

                const observer = new MutationObserver(update);
                if (rawStream) {
                    observer.observe(rawStream, { childList: true, characterData: true, subtree: true });
                }
                
                // Also poll in case observer misses rapid updates
                setInterval(update, 500);
            </script>"""

        key = "sk-c23c7cdf318c413392e48371e0efa667"
        client = OpenAI(api_key=key, base_url="https://api.deepseek.com")
        
        try:
            response = client.chat.completions.create(
                model="deepseek-chat",
                messages=[
                    {"role": "system", "content": sty},
                    {"role": "user", "content": message},
                ],
                stream=True
            )

            for chunk in response:
                if chunk.choices[0].delta.content:
                    content = chunk.choices[0].delta.content
                    safe_content = content.replace("<", "&lt;").replace(">", "&gt;")
                    yield safe_content
        except Exception as e:
            yield f"Error: {str(e)}"
        
        yield """</div>
        </body>
        </html>
        """

    return StreamingHttpResponse(event_stream(), content_type='text/html; charset=utf-8')

# 保留旧的listorders函数名用于兼容其他可能的调用，或者如果sales/urls.py指向它，我们可以重命名上面的函数或者修改urls.py。
# 这里我暂时定义 deepseek_stream_view，稍后会修改 urls.py 指向它。
# 原有的 listorders 逻辑已被 deepseek_stream_view 替代用于 /sales/deepseek/ 接口。
# 如果 /sales/orders/ 还需要 listorders，我们需要保留一个普通的 listorders。

def listorders(request):
    return HttpResponse("下面是系统中所有的订单信息。。。")

# 先定义好HTML模板
html_template = '''
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
table {
    border-collapse: collapse;
}
th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}
</style>
</head>
<body>
    <table>
    <tr>
    <th>id</th>
    <th>姓名</th>
    <th>电话号码</th>
    <th>地址</th>
    </tr>

    
    {% for customer in customers %}
      <tr>
      {% for name, value in customer.items %}
      
      <td>{{ value }}</td>
      
      {% endfor %}
      </tr>
    {% endfor %}

    </table>
</body>
</html>
'''


django_engine = engines['django']
template = django_engine.from_string(html_template)

def listcustomers(request):
    # 返回一个 QuerySet 对象 ，包含所有的表记录
    qs = Customer.objects.values()

    # 检查url中是否有参数phonenumber
    ph =  request.GET.get('phonenumber',None)

    # 如果有，添加过滤条件
    if ph:
        qs = qs.filter(phonenumber=ph)

    # 传入渲染模板需要的参数
    rendered = template.render({'customers':qs})

    return HttpResponse(rendered)







